name: broiler_buddy
description: Broiler Buddy — دليل المربّي لتربية فروج اللحم (RTL, Arabic).
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
