name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # نمرّر الأسرار كمتغيرات بيئية للـjob كله
    env:
      MY_STORE_FILE_BASE64: ${{ secrets.MY_STORE_FILE_BASE64 }}
      MY_STORE_PASSWORD:   ${{ secrets.MY_STORE_PASSWORD }}
      MY_KEY_ALIAS:        ${{ secrets.MY_KEY_ALIAS }}
      MY_KEY_PASSWORD:     ${{ secrets.MY_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Fetch packages
        run: flutter pub get

      - name: Build debug APK (unsigned)
        run: flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      # إعداد التوقيع (اختياري) — ننفّذ فقط إذا السر موجود
      - name: Set up signing (optional)
        if: ${{ env.MY_STORE_FILE_BASE64 != '' }}
        run: |
          mkdir -p "$HOME/keystore"
          echo "$MY_STO_
