name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Fetch packages
        run: flutter pub get

      - name: Build debug APK (unsigned)
        run: flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Set up signing (optional)
        if: ${{ secrets.MY_STORE_FILE_BASE64 != '' }}
        run: |
          mkdir -p $HOME/keystore
          echo "$MY_STORE_FILE_BASE64" | base64 -d > $HOME/keystore/keystore.jks
        env:
          MY_STORE_FILE_BASE64: ${{ secrets.MY_STORE_FILE_BASE64 }}

      - name: Build release AAB (signed if secrets exist)
        env:
          MY_STORE_FILE: ${{ runner.temp }}/keystore.jks
          MY_STORE_PASSWORD: ${{ secrets.MY_STORE_PASSWORD }}
          MY_KEY_ALIAS: ${{ secrets.MY_KEY_ALIAS }}
          MY_KEY_PASSWORD: ${{ secrets.MY_KEY_PASSWORD }}
        run: |
          if [ -n "${{ secrets.MY_STORE_FILE_BASE64 }}" ]; then
            echo "${{ secrets.MY_STORE_FILE_BASE64 }}" | base64 -d > $MY_STORE_FILE
          fi
          flutter build appbundle --release || true

      - name: Upload release AAB (if built)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/*.aab
          if-no-files-found: ignore
