name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # (اختياري) أسرار التوقيع إذا تريد AAB لاحقًا
    env:
      MY_STORE_FILE_BASE64: ${{ secrets.MY_STORE_FILE_BASE64 }}
      MY_STORE_PASSWORD:   ${{ secrets.MY_STORE_PASSWORD }}
      MY_KEY_ALIAS:        ${{ secrets.MY_KEY_ALIAS }}
      MY_KEY_PASSWORD:     ${{ secrets.MY_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      # JDK 17 مطلوب ل
